[2021-09-15 11:09:58] [[2021-09-15 11:09:58] [SURVEY ERROR] : [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다] : [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다
[2021-09-15 11:09:43] [[2021-09-15 11:09:43] [SURVEY ERROR] : [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다] : [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다
[2021-09-15 11:09:55] [[2021-09-15 11:09:55] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:21] [[2021-09-15 11:09:21] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:48] [[2021-09-15 11:09:48] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:10] [[2021-09-15 11:09:10] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:15] [[2021-09-15 11:09:15] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:44] [[2021-09-15 11:09:44] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:03] [[2021-09-15 11:09:03] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:21] [[2021-09-15 11:09:21] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:54] [[2021-09-15 11:09:54] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:14] [[2021-09-15 11:09:14] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:28] [[2021-09-15 11:09:28] [SURVEY ERROR] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'] : send_msg_socket() missing 2 required positional arguments: 'msg' and 'client_socket'
[2021-09-15 11:09:26] [[2021-09-15 11:09:26] [SURVEY ERROR] : 'str' object has no attribute 'values'] : 'str' object has no attribute 'values'
[2021-09-15 11:09:43] [[2021-09-15 11:09:43] [SURVEY ERROR] : 'list' object has no attribute 'appned'] : 'list' object has no attribute 'appned'
[2021-09-15 11:09:38] [[2021-09-15 11:09:38] [SURVEY ERROR] : 'list' object has no attribute 'appned'] : 'list' object has no attribute 'appned'
[2021-09-15 11:09:49] [[2021-09-15 11:09:49] [SURVEY ERROR] : 'list' object has no attribute 'appned'] : 'list' object has no attribute 'appned'
[2021-09-15 11:09:06] [[2021-09-15 11:09:06] [SURVEY ERROR] : 'list' object has no attribute 'appned'] : 'list' object has no attribute 'appned'
[2021-09-15 12:09:20] [[2021-09-15 12:09:20] [SURVEY ERROR] : 'list' object attribute 'append' is read-only] : 'list' object attribute 'append' is read-only
[2021-09-15 13:09:44] [[2021-09-15 13:09:44] [SURVEY ERROR] : local variable 'survey' referenced before assignment] : local variable 'survey' referenced before assignment
[2021-09-15 13:09:31] [[2021-09-15 13:09:31] [SURVEY ERROR] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: SELECT survey.s_id AS survey_s_id 
FROM survey 
WHERE survey.s_id = %(s_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'s_id_1': (339,), 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: SELECT survey.s_id AS survey_s_id 
FROM survey 
WHERE survey.s_id = %(s_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'s_id_1': (339,), 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-09-15 13:09:21] [[2021-09-15 13:09:21] [SURVEY ERROR] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: SELECT survey.s_id AS survey_s_id 
FROM survey 
WHERE survey.s_id = %(s_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'s_id_1': (339,), 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: SELECT survey.s_id AS survey_s_id 
FROM survey 
WHERE survey.s_id = %(s_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'s_id_1': (339,), 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-09-15 13:09:55] [[2021-09-15 13:09:55] [SURVEY ERROR] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: SELECT survey.s_id AS survey_s_id 
FROM survey 
WHERE survey.s_id = %(s_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'s_id_1': (339,), 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: SELECT survey.s_id AS survey_s_id 
FROM survey 
WHERE survey.s_id = %(s_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'s_id_1': (339,), 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-09-15 13:09:36] [[2021-09-15 13:09:36] [SURVEY ERROR] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: SELECT survey.s_id AS survey_s_id 
FROM survey 
WHERE survey.s_id = %(s_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'s_id_1': (339,), 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: SELECT survey.s_id AS survey_s_id 
FROM survey 
WHERE survey.s_id = %(s_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'s_id_1': (339,), 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-09-15 14:09:55] [[2021-09-15 14:09:55] [SURVEY ERROR] : 'NoneType' object is not subscriptable] : 'NoneType' object is not subscriptable
[2021-09-15 14:09:03] [[2021-09-15 14:09:03] [SURVEY ERROR] : name 'session' is not defined] : name 'session' is not defined
[2021-09-15 14:09:17] [[2021-09-15 14:09:17] [SURVEY ERROR] : name 'session' is not defined] : name 'session' is not defined
[2021-09-15 14:09:04] [[2021-09-15 14:09:04] [SURVEY ERROR] : (mysql.connector.errors.DatabaseError) 1366 (HY000): Incorrect integer value: 'u_id' for column 'uid' at row 1
[SQL: INSERT INTO submit (uid, created_date) VALUES (%(uid)s, %(created_date)s)]
[parameters: {'uid': 'u_id', 'created_date': datetime.datetime(2021, 9, 15, 14, 11, 4, 163692)}]
(Background on this error at: http://sqlalche.me/e/13/4xp6)] : (mysql.connector.errors.DatabaseError) 1366 (HY000): Incorrect integer value: 'u_id' for column 'uid' at row 1
[SQL: INSERT INTO submit (uid, created_date) VALUES (%(uid)s, %(created_date)s)]
[parameters: {'uid': 'u_id', 'created_date': datetime.datetime(2021, 9, 15, 14, 11, 4, 163692)}]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
[2021-09-15 14:09:01] [[2021-09-15 14:09:01] [SURVEY ERROR] : 'BaseQuery' object is not callable] : 'BaseQuery' object is not callable
[2021-09-15 14:09:10] [[2021-09-15 14:09:10] [SURVEY ERROR] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: INSERT INTO submit (uid, created_date) VALUES (%(uid)s, %(created_date)s)]
[parameters: {'uid': (205,), 'created_date': datetime.datetime(2021, 9, 15, 14, 17, 10, 282490)}]
(Background on this error at: http://sqlalche.me/e/13/f405)] : (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'result' cannot be converted to a MySQL type
[SQL: INSERT INTO submit (uid, created_date) VALUES (%(uid)s, %(created_date)s)]
[parameters: {'uid': (205,), 'created_date': datetime.datetime(2021, 9, 15, 14, 17, 10, 282490)}]
(Background on this error at: http://sqlalche.me/e/13/f405)
